language: python
python:
    - "3.7"
install:
    - pip install -r requirements.txt
script:
    - py.test
branches:
  only:
   - master
notifications:
  email:
    recipients:
      - alimzaini@outlook.com
    on_success: never
    on_failure: always